import Head from "next/head"
import Header from "@/components/Header/Header"
import Task from "@/components/Task/Task"
import { useDispatch } from "react-redux"
import { useEffect } from "react"
import { fetchTasks } from "@/store/task/taskActions"
import { resetServerContext } from "react-beautiful-dnd"

export default function Home() {
  const dispatch = useDispatch()
  useEffect(() => {
    dispatch(fetchTasks())
  }, [])

  return (
    <>
      <Head>
        <title>Task Management App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Task />
    </>
  )
}

export async function getServerSideProps(context) {
  resetServerContext()
  return { props: { data: [] } }
}
